var GAME_LEVELS = [
  ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                        xx!!!xxxx!!!xxxx                                        ",
   "                       xxx!!!xxxx!!!xxxxx                                       ",
   "                      xxxxxvxxxxxxvxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxx",
   "                     x                       xxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxx",
   "                     x                         xxxxxxxxxxxxxvxxxxxxxxxxxxxxxxx  ",
   "                     x o                                                        ",
   "                      xxx                                                       ",
   "                                      o                                         ",
   "                                     xxx                                        ",
   "                                      xx    xxxx                                ",
   "                             xxxx      x     xxxxxx                             ",
   "  @          yyy              xxx      x      xxxxxxxx                  o   o   ",
   " xxx                  xxx      xx      x      xxxxxxxxxxx           xxxxxxxxxxx ",
   "   x                 <!!!x      x      x      xxxxxxxxxxxxx       xxxxxxxxxxxxx ",
   "   x        xxx      x!!!x      x      x      xxxxxxxxxxxxx     xxxxxxxxxxxxxxx ",
   "   x       x   x     x!!!x      x      x      xxxxxxxxxxxxx o xxxxxxxxxxxxxxxxx ",
   "!!!x!!!!!!!x   x!!!!!x!!!x!!!!!!x      x      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   ["    xxxxxxxxxxxxxxxxx                                                       xxxx",
   "     xxxxxxxxxxxxxxxxxxx                                                   xxxxxx",
   "     xxxxxxx!!!!!!!xxxxxxx                                               xxxxxxxx",
   "     xxxxxx!!!!xx!!!xxxxxxxxxx                                         xxxxxxxxxx",
   "      xxxxxxvxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "              xxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "               xx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxx!!!xxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                x!!!!!!!xxxxxxxxxxxxxxx!!!!xx      xx!!!!!!xxxxxxxxxxxxxxxxxxxxx ",
   "                 xvxxxx!!!xxxxxxxxxxxxx!!xv         xxvxx!!!!!!!!!!!!!!!!!xxx    ",
   "  x @               xxxxx!xxxxxxxxxxxxx!!x              xx!!!xxxxxxxxxxxxvx      ",
   "  xxxx                 xx!!!!!!!!!!!!!!!x                xxxvxxxxxxxxxxxx        ",
   "  xxxxxxx               xxvxxxxxxxxxxxxv                     xxxxxxxxxxx         ",
   "  x xxxxxxxx               xxxxxxxxxxxx                       xxxxxxxxx          ",
   "  x    xxxxxxxx              xxxxxxxx              o           xxxxxxx           ",
   "  x       xxxxxxxx  o                            xxxxx             xx            ",
   "  x         xxxxxxxxx                         xxxxxxxxxxx                    o o ",
   "  x           xxxxxxxxxx                 o xxxxxxx   xxxxxxx                 xxxx",
   "  x             xxxxxxxxxxx o           xxxxx             xxxxx          oxxxxxx ",
   "  x                xxxxxxxxxxx       xxxxx                  xxxx o     xxxxxxx   ",
   "  x                      xxxxxxx   xxxx                         xxx   x          ",
   "  x                        xxxx!!!!!x                             x!!!x          ",
   "  x                          xx!!!!!x                             x!!!x          ",
   "!!x                           xx!!!x                              xx!xxxxxxxxxxxx"],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
